language: java
jdk:
  - oraclejdk9

before_install:
  - wget https://distfiles.macports.org/gradle/gradle-6.5-bin.zip
  - unzip -qq gradle-6.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

env:
  global:
    - TMPDIR=/tmp/